Repository GSG-G11/team-5-ecommerce-app, pull requests merged in 2022-02, with the labels that each got.

#2 Update Readme File
  .vscode/settings.json
  README.md
Labels: Done, documentation

#4 Build File structure
  .gitignore
  css/style.css
  index.html
  js/app.js
  js/logic.js
  package.json
  test/test.js
Labels: Done

#6 create fack product and Categories data
  .vscode/settings.json
  data/categories.json
  data/products.json
Labels: Awaiting Review

#10 Create test and logic for product add and delete
  js/logic.js
  test/test.js
Labels: Awaiting Review

#13 edit data json file
  data/categories.json
  data/products.json
Labels: Awaiting Review

#17 create (filter, sort) functions test & logic for products
  .editorconfig
  js/logic.js
  test/test.js
Labels: Awaiting Review

#19 create static cart
  css/cart.css
  index.html
Labels: Awaiting Review

#21 add responsive for cart section
  css/cart.css
Labels: Awaiting Review

#22 create nav bar and popup screan
  css/cart.css
  css/modal.css
  css/style.css
  img/Logo.svg
  img/Personalization-cuate_1.svg
  index.html
  js/app.js
Labels: Awaiting Review

#25 Fix Style and remove Style
  css/cart.css
  css/modal.css
  css/style.css
  index.html
Labels: Awaiting Review

#28 Create a popup screen For Create product
  css/modal.css
  css/style.css
  index.html
  js/app.js
Labels: Awaiting Review

#31 create get post products localstorage
  css/modal.css
  css/style.css
  index.html
  js/app.js
Labels: Awaiting Review

#32 add render cart function
  css/cart.css
  index.html
  js/app.js
Labels: Awaiting Review

#38 create products function add product to local and local storage
  css/modal.css
  css/style.css
  index.html
  js/app.js
  js/logic.js
  test/test.js
Labels: Awaiting Review

#43 switch between buyer and seller
  css/style.css
  js/app.js
Labels: Awaiting Review

#45 42 total price
  index.html
  js/app.js
Labels: Awaiting Review

#46 delete products function and from local storage
  js/app.js
  js/logic.js
  test/test.js
Labels: Awaiting Review

#49 sort filter products
  js/app.js
  js/logic.js
  test/test.js
Labels: Awaiting Review

#51 Fix create and delete product
  index.html
  js/app.js
Labels: Awaiting Review

#53 Create function for update and save in local storage
  index.html
  js/app.js
Labels: Awaiting Review

#54 create toggle view gird list function
  css/style.css
  js/app.js
Labels: Awaiting Review

#55 47 add item to cart
  index.html
  js/app.js
Labels: Awaiting Review

#58 create search function by name of product
  css/style.css
  js/app.js
  js/logic.js
  test/test.js
Labels: Awaiting Review

#59 57 delete item
  js/app.js
Labels: Awaiting Review

#61 background
  css/cart.css
  js/app.js
Labels: Awaiting Review
